/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Arithmetic.h"
#include "TADPilaDin.h"
#include <math.h>

void infix( char *notation );
void postfix( char *notation , char*host );
void prefix( char *notation , char *host );
void infix_to_postfix( char *notation );
void arithmetic_prg_1(char *host);
int operator_type( elemento * operator );
int parentheses( char *notation );

int main (int argc, char *argv[]){
	char *host , notation[100];
	int type;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	printf("Ingresa la expresión a evaluar:\n");
	scanf("%s",notation);
	printf("La notación es: %s\n",notation);
	printf("Ingresa el tipo de notacion (Postfija = 1 , Prefija = 2 , Infija = 3):\n");
	scanf("%d",&type);
	host = argv[1];
	switch( type ){
		case 1:
			postfix( notation , host );
			break;
		case 2:
			prefix( notation , host );
			break;
		case 3:
			infix_to_postfix( notation );
			postfix( notation , host);
			break;
		default:
			printf("Tipo de notación invalido!\n");
			break;
	}
	exit (0);
}

void infix_to_postfix( char *notation ){
	int index = 0 , size, i, type;
	elemento aux[100], post[100];
	size = strlen( notation );

	if( parentheses(notation) == 0 ){
		printf("Error! \nEl numero de parentesis no es correcto\n");
		exit(1);
	}

	pila stack;
	Initialize(&stack);

	for( i = 0; i < size ; i++ )
		aux[i].c = notation[i];

	for( i = 0 ; i < size ; i++){
		type = operator_type( &aux[i] );
		if( type < 5 )
			add_operator( aux[i] , &stack , post , &index , type );
		else
			post[index++] = aux[i];
	}

	while( Empty(&stack) == 0 )
		post[index++] = Pop( &stack );
	
	post[index].c = '\0';

	memset( notation , 0 , 100 );

	for( i=0 ; post[i].c != '\0'; i++)
		notation[i] = post[i].c;
	
	notation[i] = '\0';
}

void postfix( char *notation , char * host ){
	CLIENT *clnt;
	float *result;
	operands arg;

	#ifndef	DEBUG
		clnt = clnt_create (host, ARITHMETIC_PRG, ARTIHMETIC_VER, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif

	pila stack;
	elemento aux,value,operand1,operand2;
	int i, type;
	Initialize( &stack );
	for( i = 0 ; i < strlen( notation ) ; i++ ){
		aux.c = notation[i];
		type = operator_type( &aux );
		if( type == 6 ){
			//Evaluar trigonometrico
			Push( &stack , value );
		}
		else if( type == 5 ){
			value.f = (float) atoi( &aux.c );
			Push( &stack , value );
		}
		else{
			operand1 = Pop( &stack );
			operand2 = Pop( &stack );
			arg.operand1 = operand1.f;
			arg.operand2 = operand2.f;
			switch( aux.c ){
				case '+':
					result = addition_1(&arg, clnt);
					if (result == (float *) NULL) 
						clnt_perror (clnt, "call failed");
					value.f = *result;
				break;
				case '-':
					result = subtraction_1(&arg, clnt);
					if (result == (float *) NULL) 
					clnt_perror (clnt, "call failed");
					value.f = *result;
				break;
				case '*':
					result = multiplication_1(&arg, clnt);
					if (result == (float *) NULL) 
						clnt_perror (clnt, "call failed");
					value.f = *result;
				break;
				case '/':
					result = division_1(&arg, clnt);
					if (result == (float *) NULL)
						clnt_perror (clnt, "call failed");
					value.f = *result;
				break;
				case '^':
					//value.f = pow(operand2.f, operand1.f);
				break;
			}
			Push(&stack,value);
		}
	}
	if( Size(&stack) > 1 ){
		printf("Error!\nLa expresión tenia un error");
		exit(-1);
	}

	value = Pop( &stack );
	printf("El resultado de: %s = %f\n",notation,value.f);
	
	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
}

void prefix( char *notation , char * host ){

	CLIENT *clnt;
	float *result;
	operands arg;

	#ifndef	DEBUG
		clnt = clnt_create (host, ARITHMETIC_PRG, ARTIHMETIC_VER, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif

	pila stack;
	elemento aux,value,operand1,operand2;
	int i, type;
	Initialize( &stack );
	for( i = strlen( notation ) - 1  ; i >= 0  ; i-- ){
		aux.c = notation[i];
		type = operator_type( &aux );
		if( type == 6 ){
			//Evaluar trigonometrico
			Push( &stack , value );
		}
		else if( type == 5 ){
			value.f = (float) atoi( &aux.c );
			Push( &stack , value );
		}
		else{
			operand1 = Pop( &stack );
			operand2 = Pop( &stack );
			arg.operand1 = operand1.f;
			arg.operand2 = operand2.f;
			switch( aux.c ){
				case '+':
					result = addition_1(&arg, clnt);
					if (result == (float *) NULL) 
						clnt_perror (clnt, "call failed");
					value.f = *result;
				break;
				case '-':
					result = subtraction_1(&arg, clnt);
					if (result == (float *) NULL) 
					clnt_perror (clnt, "call failed");
					value.f = *result;
				break;
				case '*':
					result = multiplication_1(&arg, clnt);
					if (result == (float *) NULL) 
						clnt_perror (clnt, "call failed");
					value.f = *result;
				break;
				case '/':
					result = division_1(&arg, clnt);
					if (result == (float *) NULL)
						clnt_perror (clnt, "call failed");
					value.f = *result;
				break;
				case '^':
					//value.f = pow(operand2.f, operand1.f);
				break;
			}
			Push(&stack,value);
		}
	}
	if( Size(&stack) > 1 ){
		printf("Error!\nLa expresión tenia un error");
		exit(-1);
	}
	value = Pop( &stack );
	printf("El resultado de: %s = %f\n",notation,value.f);
}

int operator_type( elemento *operator ){

	if( operator->c > 64 && operator->c < 91 ) // trygonometric operator
		return 6;
	if( operator->c == '^' ) 
		return 4;
	if( operator->c == '*' || operator->c == '/' ) 
		return 3;
	if( operator->c == '-' || operator->c == '+' ) 
		return 2;
	if( operator->c == ')' ) 
		return 1;
	if( operator->c == '(' )
		return 0;
	return 5; // Is operand
}

int parentheses( char *notation ){
	int i,j,size;
	pila stack;
	elemento aux;
	size = strlen(notation);
	Initialize(&stack);

	for( i = 0; i < size ; i++){
		if( notation[i] == '(' ){
			aux.c = '(';
			Push( &stack , aux );
		}
		else if( notation[i] == ')' ){
			if( Empty(&stack) )
				return 0;
			aux = Pop( &stack );
		}
	}

	if( !Empty(&stack) )
		return 0;

	Destroy(&stack);	
	return 1;
}

void add_operator( elemento e , pila * S , elemento post[] , int * j , int type ){
	switch( type ){
	case 0:
		Push( S, e );
		break;
	case 1:
		elemento aux;
		aux = Top(S);
		while( operator_type( &aux ) != 0 ){
			post[*j] = Pop( S );
			*j++;
			aux = Top(S);
		}
		Pop(S);
		break;
	default:
		elemento aux;
		aux = Top(S);
		if( Empty(S) == 1 || type > operator_type( &aux ) )
			Push( S , e );
		else{
			elemento aux;
			aux = Top(S);
			while( Empty(S) == 1 || type  <= operator_type( &aux ) ){
				post[*j] = Pop( S );
				*j++;
				aux = Top(S);
			}
			Push( S , e );
		}
		break;
	}
}

void arithmetic_prg_1(char *host) {
	CLIENT *clnt;
	float  *result;
	operands  arg;
	float  *result_2;
	operands  subtraction_1_arg;
	float  *result_3;
	operands  division_1_arg;
	float  *result_4;
	operands  multiplication_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ARITHMETIC_PRG, ARTIHMETIC_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result = addition_1(&arg, clnt);
	if (result == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = subtraction_1(&subtraction_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = division_1(&division_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = multiplication_1(&multiplication_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}