/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Arithmetic.h"
#include "TADPilaDin.h"
#include <math.h>

void infix( char *notation );
void postfix( char *notation , char*host );
void prefix( char *notation );
void infix_to_postfix( char *notation );
void arithmetic_prg_1(char *host);
int operator_type( elemento * operator );

int main (int argc, char *argv[]){
	char *host , notation[100];
	int type;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	printf("Ingresa la notación a evaluar:\n");
	scanf("%s",notation);
	printf("La notación es: %s\n",notation);
	printf("Ingresa el tipo de notacion (Postfija = 1 , Prefija = 2 , Infija = 3):\n");
	scanf("%d",&type);
	host = argv[1];
	switch( type )
	{
	case 1:
		postfix( notation , host );
		break;
	case 2:
		prefix( notation );
		break;
	case 3:
		infix_to_postfix( notation );
		postfix( notation , host);
		break;
	default:
		printf("Tipo de notación invalido!\n");
		break;
	}
	//arithmetic_prg_1 (host);
	exit (0);
}

void infix_to_postfix( char *notation ){
	char *postfix;

}

void postfix( char *notation , char * host ){
	CLIENT *clnt;
	float  *result_1;
	operands  addition_1_arg;
	#ifndef	DEBUG
		clnt = clnt_create (host, ARITHMETIC_PRG, ARTIHMETIC_VER, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif

	pila stack;
	elemento aux,value,operand1,operand2;
	int i, type;
	Initialize( &stack );
	for( i = 0 ; i < strlen( notation ) ; i++ ){
		aux.c = notation[i];
		//printf("Entre y asigne: %c\n",aux.c);
		type = operator_type( &aux );
		if( type == 6 ){
			//Evaluar trigonometrico
			Push( &stack , value );
		}
		else if( type == 5 ){
			value.f = (float) atoi( &aux.c );
			Push( &stack , value );
		}
		else{
			operand1 = Pop( &stack );
			operand2 = Pop( &stack );
			addition_1_arg.operand1 = operand1.f;
			addition_1_arg.operand2 = operand2.f;
			switch( aux.c ){
				case '+':
					//value.f = operand1.f + operand2.f;
					result_1 = addition_1(&addition_1_arg, clnt);
					if (result_1 == (float *) NULL) 
						clnt_perror (clnt, "call failed");
					value.f = *result_1;
				break;
				case '-':
					//value.f = operand2.f - operand1.f;
					result_1 = subtraction_1(&addition_1_arg, clnt);
					if (result_1 == (float *) NULL) 
					clnt_perror (clnt, "call failed");
					value.f = *result_1;
				break;
				case '*':
					result_1 = multiplication_1(&addition_1_arg, clnt);
					if (result_1 == (float *) NULL) 
						clnt_perror (clnt, "call failed");
					value.f = *result_1;
					//value.f = operand1.f * operand2.f;
				break;
				case '/':
					result_1 = division_1(&addition_1_arg, clnt);
					if (result_1 == (float *) NULL)
						clnt_perror (clnt, "call failed");
					value.f = *result_1;
					//value.f = operand2.f / operand1.f;
				break;
				case '^':
					//value.f = pow(operand2.f, operand1.f);
				break;
			}
			Push(&stack,value);
		}
	}
	if( Size(&stack) > 1 ){
		printf("Error!\nLa expresión tenia un error");
		exit(-1);
	}
	value = Pop( &stack );
	printf("El resultado de: %s = %f\n",notation,value.f);
}

void prefix( char *notation ){
	pila stack;
	elemento aux,value,operand1,operand2;
	int i, type;
	Initialize( &stack );
	for( i = strlen( notation ) ; i >= 0  ; i-- ){
		aux.c = notation[i];
		printf("Entre y asigne: %c\n",aux.c);
		type = operator_type( &aux );
		if( type == 6 ){
			printf("Trigo?\n");
			//Evaluar trigonometrico
			Push( &stack , value );
		}
		else if( type == 5 ){
			value.f = (float) atoi( &aux.c );
			Push( &stack , value );
		}
		else{
			operand1 = Pop( &stack );
			operand2 = Pop( &stack );
			switch( aux.c ){
				case '+':
					//value.f = operand1.f + operand2.f;
				break;
				case '-':
					value.f = operand2.f - operand1.f;
				break;
				case '*':
					value.f = operand1.f * operand2.f;
				break;
				case '/':
					value.f = operand2.f / operand1.f;
				break;
				case '^':
					//value.f = pow(operand2.f, operand1.f);
				break;
			}
			Push(&stack,value);
		}
	}
	if( Size(&stack) > 1 ){
		printf("Error!\nLa expresión tenia un error");
		exit(-1);
	}
	value = Pop( &stack );
	printf("El resultado de: %s = %f\n",notation,value.f);
}

int operator_type( elemento *operator ){

	if( operator->c > 64 && operator->c < 91 ) // trygonometric operator
		return 6;
	if( operator->c == '^' ) 
		return 4;
	if( operator->c == '*' || operator->c == '/' ) 
		return 3;
	if( operator->c == '-' || operator->c == '+' ) 
		return 2;
	if( operator->c == ')' ) 
		return 1;
	if( operator->c == '(' )
		return 0;
	return 5; // Is operand
}



void arithmetic_prg_1(char *host) {
	CLIENT *clnt;
	float  *result_1;
	operands  addition_1_arg;
	float  *result_2;
	operands  subtraction_1_arg;
	float  *result_3;
	operands  division_1_arg;
	float  *result_4;
	operands  multiplication_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ARITHMETIC_PRG, ARTIHMETIC_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = addition_1(&addition_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = subtraction_1(&subtraction_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = division_1(&division_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = multiplication_1(&multiplication_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}