/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Arithmetic.h"

bool_t
xdr_operands (XDR *xdrs, operands *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->operand1))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->operand2))
		 return FALSE;
	return TRUE;
}
