/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Trigonometric.h"


void
trigonometric_prg_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	float  sine_1_arg;
	float  *result_2;
	float  cosine_1_arg;
	float  *result_3;
	float  tangent_1_arg;
	float  *result_4;
	float  cotangent_1_arg;
	float  *result_5;
	float  secant_1_arg;
	float  *result_6;
	float  cosecant_1_arg;
	float  *result_7;
	float  logarithm_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TRIGONOMETRIC_PRG, TRIGONOMETRIC_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sine_1(&sine_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = cosine_1(&cosine_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = tangent_1(&tangent_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = cotangent_1(&cotangent_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = secant_1(&secant_1_arg, clnt);
	if (result_5 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = cosecant_1(&cosecant_1_arg, clnt);
	if (result_6 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = logarithm_1(&logarithm_1_arg, clnt);
	if (result_7 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	trigonometric_prg_1 (host);
exit (0);
}
