/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Trigonometric.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
trigonometric_prg_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		float sine_1_arg;
		float cosine_1_arg;
		float tangent_1_arg;
		float cotangent_1_arg;
		float secant_1_arg;
		float cosecant_1_arg;
		float logarithm_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case sine:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) sine_1_svc;
		break;

	case cosine:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) cosine_1_svc;
		break;

	case tangent:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) tangent_1_svc;
		break;

	case cotangent:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) cotangent_1_svc;
		break;

	case secant:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) secant_1_svc;
		break;

	case cosecant:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) cosecant_1_svc;
		break;

	case logarithm:
		_xdr_argument = (xdrproc_t) xdr_float;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) logarithm_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (TRIGONOMETRIC_PRG, TRIGONOMETRIC_VER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, TRIGONOMETRIC_PRG, TRIGONOMETRIC_VER, trigonometric_prg_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (TRIGONOMETRIC_PRG, TRIGONOMETRIC_VER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, TRIGONOMETRIC_PRG, TRIGONOMETRIC_VER, trigonometric_prg_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (TRIGONOMETRIC_PRG, TRIGONOMETRIC_VER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
