/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Trigonometric.h"
#include <math.h>

float * sine_1_svc(float *argp, struct svc_req *rqstp){
	static float  result;
	result = sin( *argp );

	return &result;
}

float * cosine_1_svc(float *argp, struct svc_req *rqstp){
	static float  result;
	result = cos( *argp );

	return &result;
}

float * tangent_1_svc(float *argp, struct svc_req *rqstp){
	static float  result;
	result = tan( *argp );

	return &result;
}

float * cotangent_1_svc(float *argp, struct svc_req *rqstp){
	static float  result;
	result = 1 / tan(*argp);

	return &result;
}

float * secant_1_svc(float *argp, struct svc_req *rqstp){
	static float  result;
	result = 1 / cos( *argp );

	return &result;
}

float * cosecant_1_svc(float *argp, struct svc_req *rqstp){
	static float  result;
	result = 1 / sin( *argp );

	return &result;
}

float * logarithm_1_svc(float *argp, struct svc_req *rqstp){
	static float  result;
	result = log( *argp );

	return &result;
}
