/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Trigonometric.h"
#include <stdio.h>
#include <math.h>

float * sine_1_svc(float *argp, struct svc_req *rqstp){
	static float  result;
	result = sin( *argp );
	printf("Result: sin( %f ) = %f\n",*argp,result);

	return &result;
}

float * cosine_1_svc(float *argp, struct svc_req *rqstp){
	static float  result;
	result = cos( *argp );
	printf("Result: cos( %f ) = %f\n",*argp,result);

	return &result;
}

float * tangent_1_svc(float *argp, struct svc_req *rqstp){
	static float  result;
	result = tan( *argp );
	printf("Result: tan( %f ) = %f\n",*argp,result);

	return &result;
}

float * cotangent_1_svc(float *argp, struct svc_req *rqstp){
	static float  result;
	result = 1 / tan(*argp);
	printf("Result: cot( %f ) = %f\n",*argp,result);

	return &result;
}

float * secant_1_svc(float *argp, struct svc_req *rqstp){
	static float  result;
	result = 1 / cos( *argp );
	printf("Result: sec( %f ) = %f\n",*argp,result);

	return &result;
}

float * cosecant_1_svc(float *argp, struct svc_req *rqstp){
	static float  result;
	result = 1 / sin( *argp );
	printf("Result: csc( %f ) = %f\n",*argp,result);

	return &result;
}

float * logarithm_1_svc(float *argp, struct svc_req *rqstp){
	static float  result;
	result = log( *argp );
	printf("Result: log( %f ) = %f\n",*argp,result);

	return &result;
}
