server:	ServerHTTP.java Manejador.class Mime.class
	javac ServerHTTP.java
	java ServerHTTP
Manejador.class: Manejador.java Mime.class
	javac Manejador.java
Mime.class: Mime.java
	javac Mime.java
clean:
	rm -f *.class
