run:	Menu.class Cliente.class Ahorcado.class
	java Menu
Menu.class:	Menu.java Ahorcado.class
		javac Menu.java
Ahorcado.class:	Ahorcado.java Cliente.class
		javac Ahorcado.java
Cliente.class:  Cliente.java
		javac Cliente.java
clean:
	rm -f *.class
